use database "PORTFOLIOPROJECTS";


select  * 
from "PORTFOLIOPROJECTS"."PUBLIC"."COVIDDEATHS"
order by 3,4;


select * 
from "PORTFOLIOPROJECTS"."PUBLIC"."COVIDVACCINATION";

SELECT D.LOCATION,
    D.DATE,
    D.TOTAL_CASES,
    D.NEW_CASES,
    D.TOTAL_DEATHS,
    V.POPULATION
FROM COVIDDEATHS D
JOIN COVIDVACCINATION V
ON D.ISO_CODE= V.ISO_CODE;



-- LOOKING AT TOTAL CASES VS TOTAL DEATH

-- % DEATH AS PER CASES

SELECT LOCATION,
    DATE,
    TOTAL_CASES,
    TOTAL_DEATHS,
    (TOTAL_DEATHS/TOTAL_CASES)*100 AS "PERCENTAGE_OF_DEATH"
FROM COVIDDEATHS
WHERE TOTAL_CASES>0 AND TOTAL_DEATHS>0
ORDER BY 1,2;
----------------------------------------------------------------------------------------
-- USA DATA
-- SHOWS THE LIKELIHOOD OF DYING IF YOU CONTRACT IN YOUR COUNTRY
SELECT LOCATION,
    DATE,
    TOTAL_CASES,
    TOTAL_DEATHS,
    (TOTAL_DEATHS/TOTAL_CASES)*100 AS "PERCENTAGE_OF_DEATH"
FROM COVIDDEATHS
WHERE LOCATION LIKE '%States%'
ORDER BY 1,2;

---------------------------------------------------------------------------------------------

-- LOOKING AT TOTAL CASES  VS POPULATION
-- SHOW WHAT PERCENTAGE OF POPULATION GOT COVID
SELECT D.LOCATION,
    D.DATE,
    D.TOTAL_CASES,
    V.POPULATION, 
    (D.TOTAL_CASES/V.POPULATION)*100 AS "PERCENTAGE_OF_INFECTED_BY_POPULATION"
FROM COVIDDEATHS D
JOIN COVIDVACCINATION V
ON D.ISO_CODE= V.ISO_CODE
-- WHERE D.LOCATION LIKE '%States%'
ORDER BY 1,2
LIMIT 1000;

---------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT D.LOCATION,
    MAX(D.TOTAL_CASES) AS HIGHESTINFECTIONCOUNT,
    V.POPULATION, 
    MAX((D.TOTAL_CASES/V.POPULATION))*100 AS "PERCENTAGE_OF_INFECTED_BY_POPULATION"
FROM COVIDDEATHS D
JOIN COVIDVACCINATION V
ON D.LOCATION= V.LOCATION
GROUP BY D.LOCATION,V.POPULATION
-- WHERE D.LOCATION LIKE '%States%'
ORDER BY PERCENTAGE_OF_INFECTED_BY_POPULATION DESC
LIMIT 1000;

-----------------------------------------------------------------------------------
-- SHOWING COUNTRIES WITH HEIGHEST DEATH COUNT PER POPULATION

SELECT LOCATION, 
    MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM COVIDDEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
ORDER BY TOTALDEATHCOUNT DESC;


----------------------------------------------------------------------------------

-- LETS BREAK THINGS DOWN BY CONTINENT

SELECT CONTINENT, 
    MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM COVIDDEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY TOTALDEATHCOUNT DESC;

--------------------------------------------------------------------------
SELECT LOCATION, 
    MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM COVIDDEATHS
WHERE CONTINENT IS NULL
GROUP BY LOCATION
ORDER BY TOTALDEATHCOUNT DESC;

--------------------------------------------------------------------------
-- SHOWING THE CONTINENT WITH THE HIGHEST DEATH COUNT PER POPULATION

SELECT CONTINENT, 
    MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM COVIDDEATHS
    WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY TOTALDEATHCOUNT DESC;

-------------------------------------------------------------------------
-- GLOBAL NUMBERS

SELECT LOCATION,
    DATE,
    TOTAL_CASES,
    TOTAL_DEATHS,
    (TOTAL_DEATHS/TOTAL_CASES)*100 AS "PERCENTAGE_OF_DEATH"
FROM COVIDDEATHS
-- WHERE LOCATION LIKE '%States%'
ORDER BY 1,2;

---------------------------------------------------------------------------------
SELECT SUM(NEW_CASES) AS TOTAL_CASES,
    SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATH,
    SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS DEATHPERCENTAGE
FROM COVIDDEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2;


--------------------------------------------------------------------------------------------------------

SELECT * FROM COVIDDEATHS D
JOIN COVIDVACCINATION V
ON D.LOCATION = V.LOCATION
AND D.DATE = V.DATE;

---------------------------------------------------------------
-- LOOKING AT TOTAL POPULATION VS VACCINATION

SELECT D.CONTINENT, D.LOCATION,D.DATE,V.POPULATION, V.NEW_VACCINATIONS
FROM COVIDDEATHS D
JOIN COVIDVACCINATION V
ON D.LOCATION = V.LOCATION AND D.DATE = V.DATE
WHERE D.CONTINENT IS NOT NULL
ORDER BY 2,3;
;

------------------------------------------------------------------------------------

SELECT D.CONTINENT,
    D.LOCATION,
    D.DATE,V.POPULATION,
    V.NEW_VACCINATIONS,
    SUM(CAST(V.NEW_VACCINATIONS AS INT)) OVER(
      PARTITION BY D.LOCATION ORDER BY D.LOCATION, D.DATE) AS ROLLINGPEOPLEVACCINATED
FROM COVIDDEATHS D
JOIN COVIDVACCINATION V
ON D.LOCATION = V.LOCATION AND D.DATE = V.DATE
WHERE D.CONTINENT IS NOT NULL
ORDER BY 2,3;


-----------------------------------------------------------------------------------------------
-- USE CTE

WITH POPVSVAC (CONTINENT,LOCATION, DATE, POPULATION, NEW_VACCINATIONS, ROLLINGPEOPLEVACCINATED)
AS
(
SELECT D.CONTINENT,
    D.LOCATION,
    D.DATE,V.POPULATION,
    V.NEW_VACCINATIONS,
    SUM(CAST(V.NEW_VACCINATIONS AS INT)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION, D.DATE) AS ROLLINGPEOPLEVACCINATED
FROM COVIDDEATHS D
JOIN COVIDVACCINATION V
ON D.LOCATION = V.LOCATION AND D.DATE = V.DATE
WHERE D.CONTINENT IS NOT NULL
) 
SELECT *,(ROLLINGPEOPLEVACCINATED/POPULATION)*100 AS PERCENTAGE_OF_PEOPLE_VACCINATED
FROM POPVSVAC;


----------------------------------------------------------------------------------------------------------------------------------------
-- TEMP TABLE
SET TIMESTAMP_INPUT_FORMAT = 'YYYY-MM-DD';

CREATE OR REPLACE TABLE PERCENTPOPULATIONVACCINATED 
  ( CONTINENT NVARCHAR(255),
    LOCATION NVARCHAR(255),
   DATE DATETIME ,
   POPULATION NUMERIC,
   NEW_VACCINATIONS NUMERIC,
   ROLLINGPEOPLEVACCINATED NUMERIC);
                           
INSERT INTO PERCENTPOPULATIONVACCINATED
SELECT D.CONTINENT,
       D.LOCATION,
       V.DATE,V.POPULATION,
       V.NEW_VACCINATIONS,
       SUM(CAST(V.NEW_VACCINATIONS AS INT)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION, D.DATE) AS ROLLINGPEOPLEVACCINATED
FROM COVIDDEATHS D
JOIN COVIDVACCINATION V
ON D.LOCATION = V.LOCATION AND D.DATE = V.DATE
WHERE D.CONTINENT IS NOT NULL;


------------------------------------------------------------------------------------------------------------------------------------------

-- CREATING VIEW TO STORE DATA FOR LATER VISUALIZATION

CREATE OR REPLACE VIEW VIEW_PERCENTPOPULATIONVACCINATED AS
SELECT D.CONTINENT,
    D.LOCATION,
    D.DATE,V.POPULATION,
    V.NEW_VACCINATIONS,
    SUM(CAST(V.NEW_VACCINATIONS AS INT)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION, D.DATE) AS ROLLINGPEOPLEVACCINATED
FROM COVIDDEATHS D
JOIN COVIDVACCINATION V
ON D.LOCATION = V.LOCATION AND D.DATE = V.DATE
WHERE D.CONTINENT IS NOT NULL;

--------------------------------------------------------------------------------------------------------------------------------------------

SELECT * FROM VIEW_PERCENTPOPULATIONVACCINATED;


-- CONNECT POWER BI TO SNOWFLAKE AND VISUALIZE